### ISSUE TITLE
[PE-D][Tester C] Suggestion: Provide more appropriate error message

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-T09-3/tp#144]
For commands that require `INDEX` to be provided, for example the `delproj INDEX` command, giving the number `0` or lower causes it to fail with an invalid command error:

![telegram-cloud-photo-size-5-6260082385345426265-y.jpg](https://raw.githubusercontent.com/arnav-ag/ped/main/files/df721d44-d3d0-4f70-a38b-4b4b7be38b93.jpg)

This can be improved by parsing it as a number then telling the user that the index is an invalid number and that they need to provide a valid positive integer.

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: arnav-ag/ped#1

**Comment by Darren12345677** [comment]
We will try to make a specific error message for index when index is wrong.

**Comment by Darren12345677** [comment]
Since index is a compulsory field, we felt that it would be sensible for invalid index to show an invalid format message. We might implement a more specific error message in versions after v1.4.
