### ISSUE TITLE
[PE-D][Tester B] Mismatch between screenshot and text for Result Display in User Guide

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-T09-3/tp#145]
Please do consider changing the screenshot to display the result after the command 'addproj' is input as written in the text. Currently, it shows the result after the command 'add' is input.

![image.png](https://raw.githubusercontent.com/Vinodjayakumar124/ped/main/files/ba0c5ced-00f2-45c5-9ccd-00e128e68db8.png)

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: Vinodjayakumar124/ped#1

**Comment by Darren12345677** [comment]
Same as issue #146
