### ISSUE TITLE
[PE-D][Tester D] Screenshot not updated

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-T09-3/tp#146]
![Screenshot 2022-10-28 at 16.18.55.png](https://raw.githubusercontent.com/optionalemon/ped/main/files/08f30662-d9b2-4aa6-a877-63d4037ca377.png)

The said error output shown above, what I have gotten shown below, behavior differs from the User Guide

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: optionalemon/ped#1

**Comment by Darren12345677** [comment]
We will update user guide accordingly.
