### ISSUE TITLE
[PE-D][Tester D] Error message not shown when two errors in one input

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-T09-3/tp#155]
![Screenshot 2022-10-28 at 16.30.51.png](https://raw.githubusercontent.com/optionalemon/ped/main/files/297badd6-1732-4722-af0e-88827f1215ed.png)
 -1 is is not a whole number hence the error has been shown, but the invalid date 02-30 is not being showed as an error message to the user when coupled with the other error

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: optionalemon/ped#4

**Comment by Darren12345677** [comment]
This is intended. We may consider this for versions after v1.4
