### ISSUE TITLE
[PE-D][Tester E] Error in delstaff

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-T09-3/tp#164]
![image.png](https://raw.githubusercontent.com/tinenhao/ped/main/files/a338fa0b-2aa0-4aaf-8cb0-1422a63c73aa.png)
Error message indicates that staff index is invalid for proj aesg

![image.png](https://raw.githubusercontent.com/tinenhao/ped/main/files/b5354f23-1783-435a-a903-32988b0fac36.png)
But index should be valid based on the staff list in proj aesg

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: tinenhao/ped#4

**Comment by Darren12345677** [comment]
Same issue as #166
