### ISSUE TITLE
[PE-D][Tester E] Error in editstaff

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-T09-3/tp#166]
![image.png](https://raw.githubusercontent.com/tinenhao/ped/main/files/f0adc787-337e-48d6-b956-046357e64d8b.png)

Warning message indicates that staff index 1 is invalid in project ae sg.

![image.png](https://raw.githubusercontent.com/tinenhao/ped/main/files/f1f86fcc-a913-42c3-b7b9-cec3d42e330c.png)
But staff exists in project ae sg

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: tinenhao/ped#5

**Comment by Darren12345677** [comment]
We indicated in the user guide that editstaff can only be called onto the currently displayed staff list, so if there is no staff displayed, the command will not work. We will update the error message to make it more clear.
