### ISSUE TITLE
[PE-D][Tester D] Staff listing could be optimised

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-T09-3/tp#175]
After a few commands, user may lose track on which project the displayed staffs are in. A label to display the class that the staffs reside in may be a better alternative. 

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: optionalemon/ped#8

**Comment by Darren12345677** [comment]
Good suggestion, we will consider this for versions after v1.4.
