### ISSUE TITLE
[PE-D][Tester C] StaffName: Allows for numbers in the name

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-T09-3/tp#181]
I am not sure if numbers should be allowed for a staff name as names typically only consist of letters and spaces. I am able to add/edit a staff with the name `Test123`:

![image.png](https://raw.githubusercontent.com/arnav-ag/ped/main/files/cddde492-5bce-4218-85f3-d108cf974477.png)

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: arnav-ag/ped#9

**Comment by Darren12345677** [comment]
We will change regex to not allow numbers in staff name.

**Comment by AugustDespair** [comment]
Closed #181 as completed since it's fixed in the latest PR.
